osism/container-image-inventory-reconciler

files/ansible/playbooks/import-netbox.yml

Since we use the Netbox internally with Traefik and self-signed
certificates, we do not validate them.

netbox: do not validate certs

---

Containerfile
files/generate-inventory-from-netbox.py
files/requirements.txt
files/run.sh
files/templates/netbox.hosts.j2

This script generates an /inventory.pre/netbox.hosts
file in which all hosts defined in the netbox are stored.
The tags assigned to the hosts are used as host groups.
This script is necessary to be able to work with the
inventory defined in cfg-generics without importing it
into Netbox even when Netbox is activated.
One issue that still needs to be fixed is updating the
inventory via the reconciler when changes are made in the
Netbox.
This will be solved later via the python-osism API/Netbox
integration. When changes are made in the Netbox, a webhook
is triggered on the API, which in turn triggers an update
of the inventory.

Add generate-inventory-from-netbox script

---

files/generate-inventory-from-netbox.py

Required because of the rename of the provisioning_state custom field

Use cf_provision_state

---

files/run.sh

The respective active Ansible Runtime Environments
provide the provided versions via /interface. These
are to be used accordingly as default in the inventory.

Use versions & overlays provided via /interface

---

files/ansible/playbooks/import-netbox.yml

- Rename the modules to the ansible FQCN´s
- This is partly: osism/issues#165
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

Use the Ansible FQCN´s: container-image-inventory-reconciler repository

---

files/run.sh

This will resolve the following issue:
/run.sh: line 3: /etc/environment: No such file or directory

Check first if /etc/environment exists

---

files/sync-inventory-with-netbox.sh

Use flock to run only one sync-inventory-with-netbox.sh

---

files/run.sh

Redundancy: 
[Removed unnessecary slash in rsync target path.](https://github.com/osism/container-image-inventory-reconciler/commit/1115e7d86689298753683814c440dab6cedd5592)
["git add" and "git commit" were double, and always run. So moved outside of if-statement. ](https://github.com/osism/container-image-inventory-reconciler/commit/44db88e0d6a693ff1c81f6132ec830b9d164aa85)
Reliability:
[pushd should exit the script if directory cannot be changed. Otherwise an unexpected directory could be initialized by git. ](https://github.com/osism/container-image-inventory-reconciler/commit/fc586ff4d0985cc63b0fb3f4fc3cf334c83606d6)

improve reconciler run.sh reliability, and removed redundancy. 

---

files/generate-inventory-from-netbox.py

Also removes the managed-by-bifrost tag.

netbox: filter by maintenance & provision state

---

Containerfile
files/sync-inventory-with-netbox.sh

Does not work like expected.
This reverts commit 48114f328075a9f0f48a9947969483060e6ebe3f.

Revert "Use lockfile instead of flock (#85)"

---

.zuul.yaml

- Enable flake8 check via zuul
- Partly osism/issues#397
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

Python: Add syntax check

---

files/requirements.txt

Will be installed when required in the future via python-osism.

Remove ansible-runner from requirements

---

files/handle-inventory-overwrite.py
files/run.sh

This will avoid issues when editing files with vi or similar tools in the configuration repository on the manager.
Related to osism/issues#780

Ignore dotfiles in /inventory

---

files/prepare-vars.py

Make the fsid from the Ceph environment available as ceph_cluster_fsid for all environments. This means that ceph_cluster_fsid no longer needs to be set in environments/configuration.yml in future.
Closes osism/issues#762

Automate generation of ceph_cluster_fsid

---

files/handle-inventory-overwrite.py

At the moment we only support INI inventory files. Ignore all YAML inventory files.

Do not handle YAML files with handle-inventory-overwrite.py

---

files/run.sh

even if we have a git repository it might be the git config
is incomplete, check each entry and set it if it isn't already.
also use a more canonical way to check for a git repository
Signed-off-by: Sven Kieske <kieske@osism.tech>

account for broken/incomplete git configs

---

files/generate-inventory-from-netbox.py
files/handle-inventory-overwrite.py

As with the new version, roles defined in 20-roles, 20-netbox and 99-override will be removed from any other file. This is obviously useful for generics, but not when you have two inventory sources (from repo and netbox). 
In our case we define the manager (where netbox is deployed) in the repo, and everything else in git. The 'generic' group is then removed from the repo inventory.
I think it's fair to say we can ignore 20-roles and 20-netbox and keep them as is, as both of these sources are controlled by the user (unlike the config generics)

Prevent roles in 20-roles and 20-netbox to be removed

---

Containerfile

This solves the following problem. It can be removed in the future if netifaces is no longer used as a dependency of the OpenStack SDK.
netifaces.c:1808:9: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]

Set CFLAGS="-Wno-int-conversion"

---

files/generate-clustershell-ansible-file.py
files/generate-inventory-from-netbox.py
files/handle-inventory-overwrite.py
files/merge-ansible-cfg.py
files/merge-inventory-files.py
files/move-group-vars.py
files/prepare-vars.py

Allow configuring the log level via the OSISM_LOG_LEVEL environment variable in all Python scripts in the files directory. This provides consistent logging configuration across all inventory reconciler components. The default log level remains INFO if the environment variable is not set.

Add OSISM_LOG_LEVEL environment variable support to all Python scripts

---

files/generate-inventory-from-netbox.py
files/templates/netbox.hosts.j2

This change modifies the NetBox inventory generation to:
1. Use device roles instead of tags to assign devices to Ansible groups
2. Allow configuring multiple groups per device role via ROLE_MAPPING_<ROLE> env vars
3. Add NETBOX_IGNORED_ROLES for excluding specific device roles
4. Ensure devices have managed-by-osism tag to be considered for inventory
Example: Devices with role "compute" will be assigned to group "generic" by default, but can be customized via ROLE_MAPPING_COMPUTE env var.

netbox: use device roles instead of tags for group assignment

---

files/netbox/CLAUDE.md
files/netbox/config.py
files/netbox/netbox_client.py

Allow custom NetBox device filters via NETBOX_FILTER_INVENTORY environment variable. This enables flexible device selection based on status, tags, device type, site, or other NetBox attributes while maintaining backward compatibility with the default filter.

netbox: add configurable device filtering

---

files/netbox/data_extractor.py
files/netbox/extractors/netplan_extractor.py
files/netbox/inventory_manager.py
files/netbox/main.py

Replace device.interfaces.all() with proper API filtering by device_id as the former doesn't work correctly with pynetbox. Also fixes IP address fetching for dummy0 interfaces to use API filters. The NetBox API instance is now passed through the initialization chain from main.py to NetplanExtractor.

netbox: fix interface fetching in netplan extractor to use API filters

---

files/netbox/CLAUDE.md
files/netbox/config.py

Add configurable operating mode for the inventory reconciler with support for "manager" and "metalbox" modes. Defaults to "manager" with validation to ensure only allowed values are accepted.

netbox: add INVENTORY_RECONCILER_MODE environment parameter

---

files/netbox/CLAUDE.md
files/netbox/extractors/netplan_extractor.py

Support automatic extraction of VLAN configurations from NetBox virtual interfaces. Virtual interfaces with managed-by-osism tag, untagged VLAN, and parent interface are now included in network_vlans output with their VLAN ID, parent link, and assigned IP addresses.

netbox: add VLAN interface support to Netplan extractor

---

files/netbox/CLAUDE.md
files/netbox/extractors/netplan_extractor.py

Add validation to ensure VLAN interfaces are only included in netplan configuration when both the virtual interface and its parent interface have the managed-by-osism tag. This prevents VLANs from being configured on unmanaged parent interfaces.

netbox: require parent interface tag for VLAN configuration

---

files/netbox/device_mapping.py
files/netbox/dnsmasq_manager.py
files/netbox/inventory_manager.py
files/netbox/main.py
files/netbox/utils.py

When the 'inventory_hostname' custom field is set on a NetBox device, use it as the hostname throughout the inventory generation process instead of the device name. This allows flexibility for environments where Ansible inventory hostnames need to differ from NetBox device names.

netbox: add support for inventory_hostname custom field

---

files/netbox/data_extractor.py
files/netbox/extractors/netplan_extractor.py

Add link-local IPv6 and disable DHCP for interfaces that are:
- Connected to switches (leaf, accessleaf, dataleaf, etc.)
- Have no IPv4 or IPv6 addresses assigned
This ensures proper IPv6 link-local addressing on leaf connections while preventing DHCP on interfaces meant for BGP unnumbered setups.

netbox: add netplan parameters for leaf interfaces without IP addresses

---

files/netbox/dnsmasq_manager.py
files/netbox/netbox_client.py

Extend DHCP host entries in metalbox mode to include VLAN tags based on the untagged VLAN of each device's management-only interface. This enables VLAN-aware DHCP configuration.

netbox: add VLAN tags to DHCP host entries in metalbox mode

---

files/netbox/extractors/netplan_extractor.py

VLAN interfaces now use the MTU value from their parent interface instead of always using the default. Falls back to default MTU if parent has no MTU configured. This prevents MTU mismatches between VLAN and parent interfaces.

netbox: inherit MTU from parent interface for VLAN interfaces

---

files/netbox/dnsmasq/metalbox_mode.py

Remove redundant "vlan" prefix when creating dynamic host entries. The interface identifier already contains "vlan" in its name (e.g., "vlan123"), so adding another "vlan" prefix resulted in entries like "vlanvlan123"

netbox: fix duplicate vlan prefix in metalbox dynamic host entries

---

files/netbox/main.py

In metalbox mode, ensure FRR and Netplan parameters are always extracted and cached in NetBox custom fields, but exclude them from being written to inventory files. This allows metalbox environments to generate and cache these parameters for API access without polluting inventory files.

netbox; add metalbox mode for FRR and Netplan parameter caching

---

files/netbox/dnsmasq/metalbox_mode.py

Change from exact match to substring check for 'routed' in VLAN group names to support group names like 'routed-vlans' or 'production-routed'.

netbox: check for 'routed' substring in VLAN group names

---

files/netbox/dnsmasq/metalbox_mode.py

Updates variable names in metalbox mode handler to use '__metalbox' postfix for better organization and clarity of variable scope.

netbox: use postfix notation for dnsmasq variables in metalbox mode

---

files/netbox/main.py

In metalbox mode, config_context was not being written to host_vars for metalbox devices when NETBOX_DATA_TYPES was configured without config_context. This fix ensures metalbox devices always get their config_context written regardless of the configured data types.

netbox: ensure config_context is written for metalbox devices

---

files/netbox/gnmic/__init__.py
files/netbox/gnmic/manager.py
files/netbox/inventory/manager.py
files/netbox/main.py

Implements gnmic_parameters collection and writing for metalbox mode, similar to dnsmasq functionality:
- Created GnmicManager to collect gnmic_parameters from all devices with managed-by-metalbox tag
- Integrated GnmicManager into main workflow for metalbox mode
- Added gnmic_parameters to data extraction pipeline in metalbox mode
- Enhanced InventoryManager with data_extractor property and write_device_data_to_file method
- GNMIC targets are now aggregated and written to metalbox devices' host vars

netbox: add GNMIC parameter collection for metalbox mode

---

files/netbox/dnsmasq/dhcp_config.py

Fix https://github.com/osism/issues/issues/1273
Currently the config will break if IPv6 OOB networks are present

Skip IPv6 networks in dnsmasq

---

files/netbox/CLAUDE.md
files/netbox/config.py
files/netbox/filters.py

Adds new configuration option to allow ignoring provision state filters for Ironic devices when building inventory from NetBox.

Add INVENTORY_IGNORE_PROVISION_STATE configuration option
