- .github/workflows/release-docker-image.yml
- Containerfile
- scripts/build.sh
- scripts/push.sh
> Improve the build scripts and add the "Relase docker image" workflow

- .github/workflows/check-docker-syntax.yml
- Containerfile
> Ignore hadolint DL3003

- .github/workflows/build-container-image.yml
- .github/workflows/release-container-image.yml
- scripts/build.sh
- scripts/push.sh
> Use buildah

- files/requirements.txt
> Install celery & ansible-runner

- Containerfile
> Install python-osism

- files/ansible/plugins/filter/address.py
> Sync address.py with container-image-osism-ansible

- .github/workflows/build-container-image.yml
- .github/workflows/check-docker-syntax.yml
- .github/workflows/check-yaml-syntax.yml
partly: osism/issues#85
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
> github: run branch builds on main only

- Containerfile
> Add mapping repository

- files/generate-inventory-from-netbox.py
> Wait until the netbox is reachable

- .yamllint.yml
> Remove contrib/rally/tests/ from yamllint

- .ansible-lint
- files/ansible/playbooks/import-netbox.yml
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
> Fix Ansible-lint errors

- files/ansible/plugins/filter/address.py
> Sync address.py with kolla-ansible upstream

- files/entrypoint.sh
> Use osism service reconciler instead of osism reconciler

- .github/workflows/build-container-image.yml
- .github/workflows/release-container-image.yml
- scripts/build.sh
> github: generate sbom

- .github/workflows/release-container-image.yml
> github: use tags without leading v

- Containerfile
- files/requirements.txt
> Install osism from pypi

- files/generate-inventory-from-netbox.py
> netbox: do not add managed-by-ironic/osism host groups

- files/run.sh
- files/sync-inventory-with-netbox.sh
> Always sync the inventory with the netbox

- .ansible-lint-rules/osism_attribute_order.py
- .ansible-lint-rules/osism_fqcn.py
- files/ansible/plugins/filter/address.py
- files/handle-inventory-overwrite.py
> Autoformat python syntax with black

- Containerfile
- files/sync-inventory-with-netbox.sh
This way the use of a timeout is possible.
> Use lockfile instead of flock

- Containerfile
- files/ansible/requirements.yml
- files/requirements.txt
> Use ansible-core

- files/sync-inventory-with-netbox.sh
> netbox: check if /etc/environments exists

- files/requirements.txt
> Remove celery from requirements

- .ansible-lint
- files/ansible/playbooks/import-netbox.yml
- requirements.yml
Partly osism/issues#496
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
> Ansible-lint: Refactor ansible-lint rules

- Containerfile
- files/handle-inventory-overwrite.py
- files/merge-ansible-cfg.py
- files/render-python-requirements.py
- files/run.sh
/defaults/ansible.cfg +
/opt/configuration/environments/ansible.cfg
-->
/inventory/ansible/ansible.cfg
> Add script to merge ansible.cfg files

- .zuul.yaml
- playbooks/build.yml
We want to push the image when a tag is created.
> Add the push job to the tag pipeline

- .flake8
- Containerfile
- files/prepare-vars.py
- files/run.sh
- releasenotes/notes/prepare-vars-b0e8b404d0017074.yaml
> Add prepare-vars script

- files/handle-inventory-overwrite.py
> Handle UnicodeDecodeError exception

- playbooks/build.yml
Part of https://github.com/osism/issues/issues/894
> Relabel container

- README.md
- playbooks/build.yml
Part of https://github.com/osism/issues/issues/927
> Replace osism.github.io with osism.tech

- playbooks/build.yml
Part of https://github.com/osism/issues/issues/937
> Replace https://osism.tech/docs/intro with https://osism.tech/docs/

- files/run.sh
Related to osism/ansible-collection-services#1444
> Support the INVENTORY_FROM_NETBOX parameter

- Containerfile
- files/generate-clustershell-ansible-file.py
- files/run.sh
> In the clustershell template sort the keys

- files/change.sh
Related to 6654d0bc229711e529d4a422488d1916127804ce
> Use su instead of sudo in change.sh script

- files/run.sh
Related to ab7e0a81a1284591104496171d6dc063ae0ef6d8
> Fix check for git repository

- files/handle-inventory-overwrite.py
> Allow to overwrite inventory groups also with 20-roles

- files/generate-inventory-from-netbox.py
- files/handle-inventory-overwrite.py
Closes osism/issues#1150
Related to a5fb931c4c90030bac4d39ef66c635271d241c90
> Rename 99-netbox -> 20-netbox

- Containerfile
- files/handle-inventory-overwrite.py
- files/merge-inventory-files.py
- files/reconcile-inventory.sh
- files/run.sh
This is required to merge 20-roles & 20-netbox files.
20-roles:
[generic]
host_a
host_b
20-netbox:
[generic]
host_c
host_d
-->
20-roles:
[generic]
host_a
host_b
host_c
host_d
> Add script to merge inventory files

- files/change.sh
The git branch is in the second argument.
> Fix checkout branch in change.sh

- Containerfile
- files/render-python-requirements.py
1. Added shebang and proper documentation
- Added #!/usr/bin/env python3 for direct execution
- Added module-level docstring
2. Better code organization
- Split functionality into focused functions
- Clear separation of concerns
3. Type hints and documentation
- Added type hints for better code clarity
- Comprehensive docstrings for all functions
4. Improved error handling
- Specific exception handling for different error cases
- Informative error messages
- Proper exit codes
5. Modern Python features
- Used pathlib.Path instead of string paths
- Used yaml.safe_load() instead of yaml.load() for security
- Used f-strings for better readability
6. Better Jinja2 configuration
- Added configuration options like keep_trailing_newline
- Explicit autoescape setting
7. Main function pattern
- …
> Refactor render-python-requirements.py

- files/generate-clustershell-ansible-file.py
1. Added shebang and proper documentation
- Added #!/usr/bin/env python3 for direct execution
- Added module-level docstring explaining the script's purpose
2. Better code organization
- Split functionality into focused functions with single responsibilities
- Clearer separation of concerns
3. Type hints and documentation
- Added type hints for better code clarity
- Comprehensive docstrings for all functions
4. Improved error handling
- Removed shell=True for security (using list arguments instead)
- Better exception handling with specific error types
- Informative error messages and logging
5. Modern Python features
- Used pathlib.Path instead of string paths
- Used yaml.safe_load() instead of yaml.load() for security
- Better subprocess handling with capture_output=True and check=True …
> Refactor generate-clustershell-ansible-file.py

- files/handle-inventory-overwrite.py
1. Constants extracted
- Defined clear constants for directories, filenames, and configuration
2. Functions separated
- Split logic into focused functions for better modularity
3. Type hints added
- Added type annotations for better code documentation
4. Improved error handling
- Better exception handling with proper error messages
5. Clear file filtering
- Extracted file filtering logic for better readability
6. Comprehensive docstrings
- Added detailed documentation for all functions
7. Cleaner logger setup
- Simplified and clarified logger configuration
> Refactor refactor-handle-inventory-overwrite.py

- files/merge-ansible-cfg.py
1. Added comprehensive docstring
- Explains the script's purpose and functionality
2. Extracted constants
- File paths are now defined as constants at the top
3. Added error handling
- Robust error handling for file operations
4. Added logging
- Complete logging for debugging and monitoring
5. Added type hints
- Full type annotations for better code documentation
6. Created main function
- Proper script structure with a main entry point
7. Added validation
- Configuration file existence validation before processing
> Refactor merge-ansible-cfg.py

- files/move-group-vars.py
1. Added comprehensive documentation
- Added module-level docstring explaining the script's purpose
- Comprehensive docstrings for all functions
2. Better code organization
- Split monolithic function into focused functions (validate_directory, get_group_vars_files, etc.)
- Clear separation of concerns
- Proper main function pattern
3. Enhanced error handling
- Added try-except blocks for all I/O operations
- Specific error types (OSError, IOError)
- Informative error messages and proper logging
4. Type hints and modern Python
- Added type hints for all functions using typing module (List, Set)
- Used pathlib.Path instead of string paths
- Better path operations with Path objects
5. Improved logging
- Debug level for detailed operations
- Error level for failures
- Informative info …
> Refactor move-group-vars.py

- files/handle-inventory-overwrite.py
1. Script start logging: Added logger.info("Starting inventory overwrite handling") at the beginning of the main() function
2. Script end logging: Added logger.info("Inventory overwrite handling completed") at the end of the main() function
3. Tracking changed groups: Modified the functions to return the count of removed groups:
- remove_sections_from_file() now returns the number of sections removed
- handle_overwrite_file() now returns the total number of groups removed
- The main() function accumulates all removed groups and logs the total with logger.info(f"Removed {total_changed_groups} group(s) in total")
AI-assited: Claude Code
> Improve logging in handle-inventory-overwrite.py

- files/prepare-vars.py
1. Better structure and organization:
- Added proper module docstring
- Separated constants and configuration at the top
- Used pathlib.Path for all file operations
- Created separate functions for each distinct task
2. Improved error handling:
- Added proper exception handling in all functions
- Better error messages with context
- Functions return meaningful status values (counts or booleans)
3. Enhanced logging:
- Added start and end messages in main()
- Added statistics tracking (files written, hosts processed)
- Used appropriate log levels (info for important actions, debug for optional info)
- Consistent logging format
4. Type hints:
- Added type hints for all function parameters and return values
- Used proper imports from typing module
5. Code improvements:
- Removed unused …
> Refactor prepare-vars.py

- files/merge-inventory-files.py
1. Added comprehensive module docstring
- Explains the purpose and functionality of the script
2. Improved type hints
- Used Optional types and Path objects
3. Better separation of concerns
- Split functionality into smaller, focused functions
4. Enhanced error handling
- Better exception catching with specific error types
5. Improved logging
- Better log messages and error reporting
6. Modern Python patterns
- Used pathlib.Path instead of os.path
7. Better function documentation
- Added comprehensive docstrings for all functions
8. Consistent code style
- Following the project's conventions with constants and formatting
9. Improved main function
- Added proper exit status handling and clearer success logging
AI-assited: Claude Code
> Refactor merge-inventory-files.py

- files/merge-inventory-files.py
This has to be improved in the future.
> Do not fail when merging inventory files

- Containerfile
1. Optimized layer caching: Reordered COPY instructions to place frequently changing files later
2. Better multi-stage build: More effective use of the builder stage
3. Security improvements: Already using non-root user (dragon), added PYTHONDONTWRITEBYTECODE
4. Reduced image size: Enhanced cleanup of caches, Python bytecode, and temporary files
5. Build cache mounts: Added for UV pip installations to speed up rebuilds
> Refactor Containerfile

- files/generate-inventory-from-netbox.py
Split device retrieval in NetBox client to differentiate between:
- Devices with both managed-by-osism and managed-by-ironic tags (with active provision state requirement)
- Devices with only managed-by-osism tag (without provision state evaluation)
This allows more granular control over device filtering based on tag combinations and provision state requirements.
> netbox: extend get_managed_devices to return two sets of nodes

- files/generate-inventory-from-netbox.py
Changed the cf_maintenance filtering logic in get_managed_devices() to properly handle devices where the maintenance custom field is not set. Instead of filtering at the API level with cf_maintenance=[False], we now filter in Python to exclude only devices where maintenance is explicitly True. This allows devices with unset or None maintenance values to be included in the inventory.
> netbox: fix device filtering to allow unset maintenance field

- files/generate-inventory-from-netbox.py
Replace all file system operations with pathlib.Path for improved cross-platform compatibility and cleaner code. This refactoring includes:
- Convert all path operations from os.path to pathlib.Path
- Replace glob.glob() with Path.glob()
- Update Config dataclass to use Path objects for inventory_path and template_path
- Simplify file operations using Path methods (read_text, is_dir, mkdir)
- Add consistent encoding="utf-8" to all file operations
- Remove os.path string concatenations in favor of Path's / operator
- Update type hints to use Path instead of str for path parameters
The changes maintain backward compatibility while providing a more modern and maintainable codebase.
> refactor: modernize generate-inventory-from-netbox.py with pathlib

- files/merge-ansible-cfg.py
> refactor: modernize merge-ansible-cfg.py with pathlib

- files/generate-inventory-from-netbox.py
Add functionality to generate dnsmasq DHCP host configurations for devices with out-of-band management interfaces. The implementation extracts MAC and IP addresses from NetBox interfaces that have the 'managed-by-osism' tag and are marked as management-only.
Each device gets its own 999-netbox-dnsmasq.yml file in its host_vars directory containing the dnsmasq_dhcp_hosts parameter.
> netbox: add dnsmasq DHCP configuration generation for OOB interfaces

- files/generate-inventory-from-netbox.py
> netbox: use global settings

- files/generate-inventory-from-netbox.py
> netbox: prefer ipv4 over ipv6 primary ip address

- files/netbox/config.py
Extract default values to module-level constants and fix mutable default arguments using dataclass field factories. Add comprehensive docstrings with parameter descriptions and return types. Improve code organization and readability through consistent formatting and clearer variable naming.
> netbox: refactor config.py for improved maintainability and type safety

- files/netbox/dnsmasq_manager.py
When the inventory_hostname custom field is set, dnsmasq parameters (999-netbox-dnsmasq.yml) are now written to the host vars directory using the inventory_hostname value instead of the device name, maintaining consistency with other inventory components.
> netbox: respect inventory_hostname in dnsmasq parameter file paths

- files/netbox/dnsmasq_manager.py
In metalbox mode, collect virtual interfaces with untagged VLANs from devices with metalbox role. The dnsmasq_interfaces list contains interface names that correspond to VLANs configured in dnsmasq_dhcp_ranges, enabling VLAN-specific DHCP configuration in metalbox deployments.
> add dnsmasq_interfaces parameter for metalbox mode

- files/netbox/dnsmasq_manager.py
Add dnsmasq_dhcp_options parameter for metalbox devices to configure VLAN-specific DNS servers. For each virtual interface with an IP address and the managed-by-osism tag, generate a DHCP option entry that sets the DNS server (option 6) to the metalbox's interface IP for that VLAN.
Entry format: "tag:vlanXXX,6,ip" where XXX is the VLAN ID and ip is the metalbox interface IP address for that VLAN.
> netbox: add dnsmasq_dhcp_options for VLAN-specific DNS in metalbox mode

- files/netbox/CLAUDE.md
- files/netbox/extractors/frr_extractor.py
- files/netbox/extractors/netplan_extractor.py
> netbox: rename dummy0 interface to loopback0

- files/netbox/base.py
- files/netbox/cache.py
- files/netbox/connection.py
- files/netbox/exceptions.py
- files/netbox/filters.py
- files/netbox/interfaces.py
- files/netbox/netbox_client.py
> netbox: refactor NetBox client into modular architecture

- files/netbox/extractors/gnmi_extractor.py
Replace name-pattern matching with proper OOB interface detection using mgmt_only flag and managed-by-osism tag. Remove fallback to primary IP to ensure only true OOB interfaces are used.
> netbox: fix OOB IP extraction in GNMI extractor
